-- Elite Influencer Database Schema
-- This file documents the structure of the 'portfolios' table.
-- Run this in the Supabase SQL Editor to create the table or reference it for development.

-- Enable Row Level Security (RLS) is recommended but not strictly required for this demo.
-- create extension if not exists "uuid-ossp";

CREATE TABLE IF NOT EXISTS portfolios (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  -- Identity
  username text UNIQUE NOT NULL, -- e.g. "john_doe"
  full_name text,                -- e.g. "John Doe"
  tagline text,                  -- e.g. "Digital Creator | Filmmaker"
  bio text,                      -- e.g. "I create content for..."
  city text,                     -- e.g. "New York, USA"
  
  -- Status
  is_available boolean DEFAULT true,
  
  -- Contact
  contact_email text,
  contact_phone text,
  
  -- Social Proof (Brands)
  brands text[], -- Array of strings, e.g. ["Nike", "Adidas"]
  
  -- Flexible Stats & Platform Data (JSONB)
  -- Schema for 'stats':
  -- {
  --   "followers": "10k",
  --   "reach": "50k",
  --   "platform": "instagram" | "youtube",
  --   "platform_url": "https://instagram.com/john_doe"
  -- }
  stats jsonb DEFAULT '{}'::jsonb,
  
  -- Work Links (Videos) (JSONB)
  -- Schema for 'work_links':
  -- [
  --   { "title": "My Viral Video", "url": "https://youtube.com/watch?v=..." },
  --   { "title": "Brand Collab", "url": "https://instagram.com/reel/..." }
  -- ]
  work_links jsonb DEFAULT '[]'::jsonb
);

-- Recommended RLS Policies (Enabled for Production)
ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can view portfolios
CREATE POLICY "Public profiles are viewable by everyone" 
ON portfolios FOR SELECT 
USING ( true );

-- Policy: Users can only update their own portfolio
CREATE POLICY "Users can update own portfolio" 
ON portfolios FOR UPDATE 
USING ( auth.uid() = user_id );

-- Policy: Users can insert their own portfolio
CREATE POLICY "Users can insert own portfolio" 
ON portfolios FOR INSERT 
WITH CHECK ( auth.uid() = user_id );

----------------------------------------------------------------
-- Leads Table (Public Form Submissions)
----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
  id bigint generated by default as identity not null primary key,
  created_at timestamptz DEFAULT now(),
  name text,
  email text,
  instagram text,
  phone text,
  quote_price text,
  niche_category text,
  experience_level text,
  city text,
  followers text
);

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow public to INSERT (Required for the Contact Form)
-- Note: Supabase may flag this as "unsafe" because it allows anyone to write.
-- This is intentional for a public contact form.
CREATE POLICY "Enable insert for everyone" 
ON leads FOR INSERT 
WITH CHECK ( true );

-- Policy 2: Restrict SELECT to Service Role only (or Admin users)
-- No "USING (true)" policy here means public CANNOT read the data.
-- Only the dashboard owner can view leads in the Supabase Table Editor.
CREATE POLICY "Enable select for service role only" 
ON leads FOR SELECT 
USING ( auth.role() = 'service_role' );
