-- Elite Influencer Database Schema
-- This file documents the structure of the 'portfolios' table.
-- Run this in the Supabase SQL Editor to create the table or reference it for development.
--
-- IMPORTANT: after running this file, also run migration_security_fixes.sql
-- (adds the admins table, locks down brand_offers/articles to admins only,
-- adds portfolios.profile_image + is_verified, and the avatars storage bucket).

-- Enable Row Level Security (RLS) is recommended but not strictly required for this demo.
-- create extension if not exists "uuid-ossp";

CREATE TABLE IF NOT EXISTS portfolios (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  -- Identity
  username text UNIQUE NOT NULL, -- e.g. "john_doe"
  full_name text,                -- e.g. "John Doe"
  tagline text,                  -- e.g. "Digital Creator | Filmmaker"
  bio text,                      -- e.g. "I create content for..."
  city text,                     -- e.g. "New York, USA"
  
  -- Status
  is_available boolean DEFAULT true,
  
  -- Contact
  contact_email text,
  contact_phone text,
  
  -- Social Proof (Brands)
  brands text[], -- Array of strings, e.g. ["Nike", "Adidas"]
  
  -- Flexible Stats & Platform Data (JSONB)
  -- Schema for 'stats':
  -- {
  --   "followers": "10k",
  --   "reach": "50k",
  --   "platform": "instagram" | "youtube",
  --   "platform_url": "https://instagram.com/john_doe"
  -- }
  stats jsonb DEFAULT '{}'::jsonb,
  
  -- Work Links (Videos) (JSONB)
  -- Schema for 'work_links':
  -- [
  --   { "title": "My Viral Video", "url": "https://youtube.com/watch?v=..." },
  --   { "title": "Brand Collab", "url": "https://instagram.com/reel/..." }
  -- ]
  work_links jsonb DEFAULT '[]'::jsonb
);

-- Trigger for updated_at
CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;
DROP TRIGGER IF EXISTS handle_updated_at ON portfolios;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON portfolios
  FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime(updated_at);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_portfolios_available ON portfolios(is_available);

-- Recommended RLS Policies (Enabled for Production)
ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can view portfolios
CREATE POLICY "Public profiles are viewable by everyone" 
ON portfolios FOR SELECT 
USING ( true );

-- Policy: Users can only update their own portfolio
CREATE POLICY "Users can update own portfolio" 
ON portfolios FOR UPDATE 
USING ( auth.uid() = user_id );

-- Policy: Users can insert their own portfolio
CREATE POLICY "Users can insert own portfolio" 
ON portfolios FOR INSERT 
WITH CHECK ( auth.uid() = user_id );

----------------------------------------------------------------
-- Leads Table (Public Form Submissions)
----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
  id bigint generated by default as identity not null primary key,
  created_at timestamptz DEFAULT now(),
  name text,
  email text,
  instagram text,
  phone text,
  quote_price text,
  niche_category text,
  experience_level text,
  city text,
  followers text
);

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow public to INSERT (Required for the Contact Form)
-- Note: Supabase may flag this as "unsafe" because it allows anyone to write.
-- This is intentional for a public contact form.
CREATE POLICY "Enable insert for everyone" 
ON leads FOR INSERT 
WITH CHECK ( true );

-- Policy 2: Restrict SELECT to Service Role only (or Admin users)
-- No "USING (true)" policy here means public CANNOT read the data.
-- Only the dashboard owner can view leads in the Supabase Table Editor.
CREATE POLICY "Enable select for service role only" 
ON leads FOR SELECT 
USING ( auth.role() = 'service_role' );

----------------------------------------------------------------
-- Articles Table (Admin Only Creation)
----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS articles (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  published boolean DEFAULT true,
  image_url text
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_articles_published ON articles(published);

ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Policy 1: Public can read published articles
DROP POLICY IF EXISTS "Public can view published articles" ON articles;
CREATE POLICY "Public can view published articles"
ON articles FOR SELECT
USING ( published = true );

-- Policy 2: Admin/Owner can insert their own articles
DROP POLICY IF EXISTS "Users can insert own articles" ON articles;
CREATE POLICY "Users can insert own articles"
ON articles FOR INSERT
WITH CHECK ( auth.uid() = author_id );

-- Policy 3: Admin/Owner can update their own articles
DROP POLICY IF EXISTS "Users can update own articles" ON articles;
CREATE POLICY "Users can update own articles"
ON articles FOR UPDATE
USING ( auth.uid() = author_id );

-- Policy 4: Admin/Owner can delete their own articles
DROP POLICY IF EXISTS "Users can delete own articles" ON articles;
CREATE POLICY "Users can delete own articles"
ON articles FOR DELETE
USING ( auth.uid() = author_id );

----------------------------------------------------------------
-- Brand Offers Table (Admin Only Creation)
----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS brand_offers (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  brand_name text NOT NULL,
  budget text NOT NULL,
  niche text NOT NULL,
  requirements text NOT NULL,
  logo_url text,
  is_active boolean DEFAULT true,
  admin_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  follower_range text,
  apply_link text NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_brand_offers_active ON brand_offers(is_active);

ALTER TABLE brand_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view active offers"
ON brand_offers FOR SELECT
USING ( is_active = true );

CREATE POLICY "Admin can insert offers"
ON brand_offers FOR INSERT
WITH CHECK ( auth.uid() = admin_id );

CREATE POLICY "Admin can update offers"
ON brand_offers FOR UPDATE
USING ( auth.uid() = admin_id );

CREATE POLICY "Admin can delete offers"
ON brand_offers FOR DELETE
USING ( auth.uid() = admin_id );
